version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  test_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: test_prisma
    volumes:
      - ./data/test_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
