openapi: 3.0.0
info:
  title: Pollution API
  version: 1.0.0
paths:
  /v1/pollution:
    get:
      summary: Gets pollution data for the nearest city to a given set of coordinates
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: string
        - name: longitude
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A PollutionData object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PollutionData"
components:
  schemas:
    PollutionData:
      type: object
      properties:
        Result:
          type: object
          properties:
            Pollution:
              type: object
              properties:
                ts:
                  type: string
                  example: "2024-02-02T15:33:19Z"
                aqius:
                  type: number
                  example: 42
                mainus:
                  type: string
                  example: "p2"
                aqicn:
                  type: number
                  example: 20
                maincn:
                  type: string
                  example: "pm25"
